# workflow의 이름
name: CI

# 해당 workflow가 언제 실행될지 정의한다.
on:
  push: # master branch로 push 될 때 실행
    branches: [ "main" ]

#workflow는 1개 이상의 job을 가지며, 각각의 job은 여러 개의 step에 따라 단계를 나눌 수 있다.
jobs:
  build: #작업 이름을 build라 지정
    runs-on: ubuntu-latest # 해당 작업이 실행되는 환경을 정의한다. - 우분투 최신버전

    steps: # 작업이 실행되는 단계들을 정의
    - uses: actions/checkout@v3 #checkout 액션을 사용해서 현재 레파지토리의 코드를 체크아웃 한다. (@V3은 액션의 버전)
    - name: Set up JDK 17 # step의 이름을 정의
      uses: actions/setup-java@v3 #setup-java 액션을 사용하여 자바 설정, with를 통해 버전 명시
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip
